emr_analytics:
  outputs:
    dev:
      type: bigquery
      project: "{{ env_var('ANALYTICS_BQ_PROJECT_ID') }}" 
      dataset: "{{ env_var('ANALYTICS_BQ_DATASET') }}" 
      job_execution_timeout_seconds: 400
      job_retries: 1      
      keyfile: "{{ env_var('DBT_DATABASE_CREDENTIALS') }}"
      location: EU # need env variable
      method: service-account
      priority: interactive      
      threads: 1      
  target: dev
